# Market Research System v1.0 - Security Configuration
# Created: January 2022
# Updated: December 2022

# API Security Settings
api_security:
  encryption:
    encrypt_api_keys: true
    encryption_algorithm: "AES-256"
    key_rotation_days: 90
    
  authentication:
    require_api_key_authentication: true
    api_key_header_name: "X-API-KEY"
    session_timeout_minutes: 60
    max_failed_attempts: 5
    lockout_duration_minutes: 30
    
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    requests_per_hour: 1000
    requests_per_day: 10000
    burst_limit: 10
    
  ssl_tls:
    require_https: true
    min_tls_version: "1.2"
    verify_ssl_certificates: true
    certificate_path: "/etc/ssl/certs/"
    
# Data Security
data_security:
  encryption:
    encrypt_sensitive_data: true
    encryption_at_rest: true
    encryption_in_transit: true
    key_management_service: "local"  # local, aws_kms, azure_key_vault
    
  access_control:
    enable_file_permissions: true
    data_directory_permissions: "750"
    log_directory_permissions: "755"
    config_directory_permissions: "750"
    
  data_sanitization:
    sanitize_input_data: true
    remove_pii_from_logs: true
    anonymize_user_data: false  # Set to true if handling user data
    
  backup_security:
    encrypt_backups: true
    secure_backup_location: true
    backup_access_logging: true
    
# Network Security
network_security:
  firewall:
    enable_ip_whitelist: false
    allowed_ip_ranges: []
    block_suspicious_ips: true
    
  proxy_settings:
    use_proxy: false
    proxy_host: ""
    proxy_port: 0
    proxy_authentication: false
    
  dns_security:
    use_secure_dns: true
    dns_servers:
      - "8.8.8.8"
      - "8.8.4.4"
    validate_dns_responses: true
    
# Authentication and Authorization
auth:
  user_management:
    enable_user_accounts: false  # Simple system, file-based access
    default_user_role: "analyst"
    password_policy:
      min_length: 12
      require_uppercase: true
      require_lowercase: true
      require_numbers: true
      require_special_chars: true
      password_expiry_days: 90
      
  session_management:
    secure_session_cookies: true
    httponly_cookies: true
    samesite_cookies: "strict"
    session_regeneration: true
    
# Logging and Monitoring Security
security_logging:
  log_security_events: true
  security_log_file: "logs/security/security.log"
  log_failed_authentications: true
  log_api_access: true
  log_file_access: true
  log_configuration_changes: true
  
  alert_on_events:
    - failed_authentication_attempts
    - suspicious_api_usage
    - unauthorized_file_access
    - configuration_changes
    - system_errors
    
  log_retention:
    security_logs_retention_days: 365
    rotate_logs_daily: true
    compress_old_logs: true
    
# Input Validation and Sanitization
input_validation:
  validate_all_inputs: true
  sanitize_file_paths: true
  validate_api_responses: true
  check_data_integrity: true
  
  allowed_file_types:
    - ".csv"
    - ".json"
    - ".yaml"
    - ".xml"
    
  blocked_file_types:
    - ".exe"
    - ".bat"
    - ".sh"
    - ".ps1"
    
# Error Handling Security
error_handling:
  hide_sensitive_errors: true
  log_all_errors: true
  sanitize_error_messages: true
  disable_debug_in_production: true
  
# Third-party Security
third_party:
  dependency_scanning: false  # Manual review for 2022
  verify_package_signatures: false
  use_trusted_repositories: true
  
  trusted_domains:
    - "finance.yahoo.com"
    - "api.stlouisfed.org"
    - "pypi.org"
    - "github.com"
    
# System Security
system_security:
  file_system:
    enable_file_integrity_monitoring: false
    restrict_file_permissions: true
    disable_unnecessary_services: true
    
  process_security:
    run_as_non_root: true
    limit_process_privileges: true
    enable_process_isolation: false
    
  memory_security:
    clear_sensitive_memory: true
    disable_core_dumps: true
    enable_stack_protection: true
    
# Compliance and Auditing
compliance:
  enable_audit_trail: true
  audit_log_file: "logs/audit/audit.log"
  audit_retention_days: 1095  # 3 years
  
  gdpr_compliance:
    enabled: false  # No personal data handling
    data_retention_policy: false
    right_to_deletion: false
    
  financial_compliance:
    sox_compliance: false
    mifid_compliance: false
    record_keeping_years: 7
    
# Incident Response
incident_response:
  enable_automated_response: false
  incident_log_file: "logs/security/incidents.log"
  
  response_actions:
    block_suspicious_ips: false
    rate_limit_aggressive_users: true
    alert_administrators: false
    
  notification_settings:
    email_alerts: false
    slack_alerts: false
    sms_alerts: false
    
# Development Security (for 2022 context)
development:
  code_security:
    static_analysis: false  # Manual code review
    dependency_check: false  # Manual dependency review
    secrets_scanning: false  # Manual secrets management
    
  secure_coding:
    input_validation_required: true
    output_encoding_required: true
    sql_injection_prevention: true
    xss_prevention: true
    
# Environment-specific Security
environments:
  development:
    relaxed_security: true
    debug_mode_allowed: true
    test_data_usage: true
    
  production:
    strict_security: true
    debug_mode_forbidden: true
    full_logging_enabled: true
    
  testing:
    isolated_environment: true
    test_data_only: true
    limited_network_access: true